// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsOtel")>]
[<assembly: AssemblyProductAttribute("FsLibLog")>]
[<assembly: AssemblyVersionAttribute("0.9.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-11-21T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.9.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.9.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","6c694625d3a5ce836b519fe1e3867323980b47c1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsOtel"
    let [<Literal>] AssemblyProduct = "FsLibLog"
    let [<Literal>] AssemblyVersion = "0.9.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-11-21T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.9.0"
    let [<Literal>] AssemblyInformationalVersion = "0.9.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "6c694625d3a5ce836b519fe1e3867323980b47c1"
